using System.Text;

namespace Pi.Tui;

/// <summary>
/// CJK predicates ported from <c>utils.ts</c>. The TypeScript regexes are built on
/// <c>\p{Script_Extensions=Han|Hiragana|Katakana|Hangul|Bopomofo}</c>, which .NET regular
/// expressions cannot express, so the code point sets are materialised as range tables in
/// <see cref="JsCjkData"/> (generated by probing the original regexes; see T24 in
/// <c>docs/tui-porting-status.md</c>).
/// </summary>
internal static class JsCjk
{
    /// <summary>
    /// TS <c>cjkBreakRegex.test(segment)</c> - a CJK line-break opportunity. The regex has no anchor
    /// and no <c>g</c> flag, so it matches when <em>any</em> rune of the argument is CJK; every
    /// existing caller passes a single grapheme, where that is the same as testing the first rune.
    /// </summary>
    public static bool IsCjkBreak(string segment)
    {
        if (segment.Length == 0)
        {
            return false;
        }

        foreach (var rune in segment.EnumerateRunes())
        {
            if (JsString.InRanges(JsCjkData.CjkBreakRanges, rune.Value))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>TS <c>cjkPunctuationRegex.test(character)</c> - CJK prose punctuation.</summary>
    public static bool IsCjkPunctuation(int codePoint) =>
        JsString.InRanges(JsCjkData.CjkPunctuationRanges, codePoint);

    /// <summary>
    /// TS <c>autocompleteSeparatorRegex</c> - <c>\s</c> or CJK punctuation. Everything the
    /// unquoted autocomplete suffix may not contain.
    /// </summary>
    public static bool IsAutocompleteSeparator(int codePoint) =>
        (codePoint <= 0xFFFF && JsString.IsWhitespace((char)codePoint)) || IsCjkPunctuation(codePoint);

    /// <summary>Code point of the first rune in <paramref name="value"/>, or -1 when empty.</summary>
    public static int RuneAt(string value)
    {
        if (value.Length == 0)
        {
            return -1;
        }

        var rune = value.EnumerateRunes().First();
        return rune.Value;
    }
}
