namespace Pi.Tui;

/// <summary>
/// Lookup tables for <see cref="Latex"/>, generated 1:1 from the TS <c>latex.ts</c> constants.
/// Kept separate from the parser so the tables can be diffed against the upstream source at a glance.
/// Invisible code points (combining marks, private-use sentinels, format characters) are written as
/// <c>\uXXXX</c> escapes so they stay reviewable.
/// </summary>
internal static class LatexData
{
    /// <summary>Command name to rendered symbol.</summary>
    public static readonly Dictionary<string, string> Symbols = new()
    {
        ["alpha"] = "α",
        ["beta"] = "β",
        ["gamma"] = "γ",
        ["delta"] = "δ",
        ["epsilon"] = "ϵ",
        ["varepsilon"] = "ε",
        ["zeta"] = "ζ",
        ["eta"] = "η",
        ["theta"] = "θ",
        ["vartheta"] = "ϑ",
        ["iota"] = "ι",
        ["kappa"] = "κ",
        ["varkappa"] = "ϰ",
        ["lambda"] = "λ",
        ["mu"] = "μ",
        ["nu"] = "ν",
        ["xi"] = "ξ",
        ["pi"] = "π",
        ["varpi"] = "ϖ",
        ["rho"] = "ρ",
        ["varrho"] = "ϱ",
        ["sigma"] = "σ",
        ["varsigma"] = "ς",
        ["tau"] = "τ",
        ["upsilon"] = "υ",
        ["phi"] = "ϕ",
        ["varphi"] = "φ",
        ["chi"] = "χ",
        ["psi"] = "ψ",
        ["omega"] = "ω",
        ["Gamma"] = "Γ",
        ["Delta"] = "Δ",
        ["Theta"] = "Θ",
        ["Lambda"] = "Λ",
        ["Xi"] = "Ξ",
        ["Pi"] = "Π",
        ["Sigma"] = "Σ",
        ["Upsilon"] = "Υ",
        ["Phi"] = "Φ",
        ["Psi"] = "Ψ",
        ["Omega"] = "Ω",
        ["pm"] = "±",
        ["mp"] = "∓",
        ["times"] = "×",
        ["div"] = "÷",
        ["cdot"] = "·",
        ["ast"] = "∗",
        ["star"] = "⋆",
        ["circ"] = "∘",
        ["bullet"] = "•",
        ["oplus"] = "⊕",
        ["ominus"] = "⊖",
        ["otimes"] = "⊗",
        ["oslash"] = "⊘",
        ["odot"] = "⊙",
        ["bigcirc"] = "○",
        ["dagger"] = "†",
        ["ddagger"] = "‡",
        ["amalg"] = "⨿",
        ["uplus"] = "⊎",
        ["sqcap"] = "⊓",
        ["sqcup"] = "⊔",
        ["bowtie"] = "⋈",
        ["Join"] = "⋈",
        ["ltimes"] = "⋉",
        ["rtimes"] = "⋊",
        ["leftouterjoin"] = "⟕",
        ["rightouterjoin"] = "⟖",
        ["fullouterjoin"] = "⟗",
        ["triangleleft"] = "◁",
        ["triangleright"] = "▷",
        ["wr"] = "≀",
        ["cap"] = "∩",
        ["cup"] = "∪",
        ["bigcap"] = "⋂",
        ["bigcup"] = "⋃",
        ["bigwedge"] = "⋀",
        ["bigvee"] = "⋁",
        ["bigsqcup"] = "⨆",
        ["biguplus"] = "⨄",
        ["bigoplus"] = "⨁",
        ["bigotimes"] = "⨂",
        ["bigodot"] = "⨀",
        ["setminus"] = "∖",
        ["in"] = "∈",
        ["notin"] = "∉",
        ["ni"] = "∋",
        ["subset"] = "⊂",
        ["supset"] = "⊃",
        ["subseteq"] = "⊆",
        ["supseteq"] = "⊇",
        ["sqsubset"] = "⊏",
        ["sqsupset"] = "⊐",
        ["sqsubseteq"] = "⊑",
        ["sqsupseteq"] = "⊒",
        ["prec"] = "≺",
        ["preceq"] = "≼",
        ["succ"] = "≻",
        ["succeq"] = "≽",
        ["ll"] = "≪",
        ["gg"] = "≫",
        ["le"] = "≤",
        ["leq"] = "≤",
        ["leqslant"] = "≤",
        ["ge"] = "≥",
        ["geq"] = "≥",
        ["geqslant"] = "≥",
        ["ne"] = "≠",
        ["neq"] = "≠",
        ["equiv"] = "≡",
        ["approx"] = "≈",
        ["sim"] = "∼",
        ["simeq"] = "≃",
        ["cong"] = "≅",
        ["asymp"] = "≍",
        ["doteq"] = "≐",
        ["propto"] = "∝",
        ["parallel"] = "∥",
        ["perp"] = "⊥",
        ["mid"] = "∣",
        ["vdash"] = "⊢",
        ["dashv"] = "⊣",
        ["models"] = "⊨",
        ["Vdash"] = "⊩",
        ["Vvdash"] = "⊪",
        ["nvdash"] = "⊬",
        ["nvDash"] = "⊭",
        ["forall"] = "∀",
        ["exists"] = "∃",
        ["nexists"] = "∄",
        ["neg"] = "¬",
        ["land"] = "∧",
        ["wedge"] = "∧",
        ["lor"] = "∨",
        ["vee"] = "∨",
        ["to"] = "→",
        ["rightarrow"] = "→",
        ["longrightarrow"] = "→",
        ["leftarrow"] = "←",
        ["longleftarrow"] = "←",
        ["gets"] = "←",
        ["leftrightarrow"] = "↔",
        ["longleftrightarrow"] = "↔",
        ["hookleftarrow"] = "↩",
        ["hookrightarrow"] = "↪",
        ["twoheadleftarrow"] = "↞",
        ["twoheadrightarrow"] = "↠",
        ["leftharpoonup"] = "↼",
        ["leftharpoondown"] = "↽",
        ["rightharpoonup"] = "⇀",
        ["rightharpoondown"] = "⇁",
        ["rightleftharpoons"] = "⇌",
        ["leftrightharpoons"] = "⇋",
        ["nearrow"] = "↗",
        ["searrow"] = "↘",
        ["swarrow"] = "↙",
        ["nwarrow"] = "↖",
        ["rightsquigarrow"] = "⇝",
        ["leadsto"] = "⇝",
        ["Rightarrow"] = "⇒",
        ["Longrightarrow"] = "⇒",
        ["Leftarrow"] = "⇐",
        ["Longleftarrow"] = "⇐",
        ["Leftrightarrow"] = "⇔",
        ["Longleftrightarrow"] = "⇔",
        ["implies"] = "⇒",
        ["iff"] = "⇔",
        ["mapsto"] = "↦",
        ["longmapsto"] = "↦",
        ["uparrow"] = "↑",
        ["downarrow"] = "↓",
        ["partial"] = "∂",
        ["nabla"] = "∇",
        ["int"] = "∫",
        ["iint"] = "∬",
        ["iiint"] = "∭",
        ["oint"] = "∮",
        ["sum"] = "∑",
        ["prod"] = "∏",
        ["coprod"] = "∐",
        ["infty"] = "∞",
        ["emptyset"] = "∅",
        ["varnothing"] = "∅",
        ["angle"] = "∠",
        ["therefore"] = "∴",
        ["because"] = "∵",
        ["aleph"] = "ℵ",
        ["beth"] = "ℶ",
        ["gimel"] = "ℷ",
        ["daleth"] = "ℸ",
        ["top"] = "⊤",
        ["bot"] = "⊥",
        ["triangle"] = "△",
        ["square"] = "□",
        ["lozenge"] = "◊",
        ["checkmark"] = "✓",
        ["complement"] = "∁",
        ["wp"] = "℘",
        ["prime"] = "′",
        ["ldots"] = "…",
        ["dots"] = "…",
        ["cdots"] = "⋯",
        ["vdots"] = "⋮",
        ["ddots"] = "⋱",
        ["ell"] = "ℓ",
        ["hbar"] = "ℏ",
        ["Im"] = "ℑ",
        ["Re"] = "ℜ",
        ["langle"] = "⟨",
        ["rangle"] = "⟩",
        ["vert"] = "|",
        ["lvert"] = "|",
        ["rvert"] = "|",
        ["Vert"] = "‖",
        ["lVert"] = "‖",
        ["rVert"] = "‖",
        ["lbrace"] = "{",
        ["rbrace"] = "}",
        ["backslash"] = "\\",
        ["lfloor"] = "⌊",
        ["rfloor"] = "⌋",
        ["lceil"] = "⌈",
        ["rceil"] = "⌉",
        ["colon"] = ":",
    };

    /// <summary>Operators rendered as their own name (sin, lim, ...).</summary>
    public static readonly HashSet<string> NamedOperators = new()
    {
        "arccos",
        "arcsin",
        "arctan",
        "arg",
        "cos",
        "cosh",
        "cot",
        "coth",
        "csc",
        "deg",
        "det",
        "dim",
        "exp",
        "gcd",
        "hom",
        "inf",
        "ker",
        "lg",
        "lim",
        "liminf",
        "limsup",
        "ln",
        "log",
        "max",
        "min",
        "Pr",
        "sec",
        "sin",
        "sinh",
        "sup",
        "tan",
        "tanh",
    };

    /// <summary>Operators that take limits.</summary>
    public static readonly HashSet<string> LimitOperators = new()
    {
        "argmax",
        "argmin",
        "inf",
        "injlim",
        "lim",
        "liminf",
        "limsup",
        "max",
        "min",
        "projlim",
        "sup",
    };

    /// <summary>Large operators that take display limits.</summary>
    public static readonly HashSet<string> DisplayLimitSymbols = new()
    {
        "bigcap",
        "bigcup",
        "bigodot",
        "bigoplus",
        "bigotimes",
        "bigsqcup",
        "biguplus",
        "bigvee",
        "bigwedge",
        "coprod",
        "int",
        "iint",
        "iiint",
        "oint",
        "prod",
        "sum",
    };

    /// <summary>Relations get spacing around them.</summary>
    public static readonly HashSet<string> RelationCommands = new()
    {
        "Leftarrow",
        "Leftrightarrow",
        "Longleftarrow",
        "Longleftrightarrow",
        "Longrightarrow",
        "Rightarrow",
        "Join",
        "Vdash",
        "Vvdash",
        "approx",
        "asymp",
        "bowtie",
        "cong",
        "dashv",
        "fullouterjoin",
        "doteq",
        "downarrow",
        "equiv",
        "ge",
        "geq",
        "geqslant",
        "gets",
        "gg",
        "hookleftarrow",
        "hookrightarrow",
        "iff",
        "implies",
        "in",
        "leadsto",
        "le",
        "leftarrow",
        "leftharpoondown",
        "leftharpoonup",
        "leftrightarrow",
        "leftrightharpoons",
        "leftouterjoin",
        "leq",
        "leqslant",
        "ll",
        "longleftarrow",
        "longleftrightarrow",
        "longmapsto",
        "longrightarrow",
        "ltimes",
        "mapsto",
        "mid",
        "models",
        "ne",
        "nearrow",
        "neq",
        "ni",
        "notin",
        "nvdash",
        "nvDash",
        "nwarrow",
        "parallel",
        "perp",
        "prec",
        "preceq",
        "propto",
        "rightharpoondown",
        "rightharpoonup",
        "rightleftharpoons",
        "rightouterjoin",
        "rightarrow",
        "rightsquigarrow",
        "rtimes",
        "searrow",
        "sim",
        "simeq",
        "sqsubset",
        "sqsubseteq",
        "sqsupset",
        "sqsupseteq",
        "subset",
        "subseteq",
        "succ",
        "succeq",
        "supset",
        "supseteq",
        "swarrow",
        "to",
        "triangleleft",
        "triangleright",
        "twoheadleftarrow",
        "twoheadrightarrow",
        "uparrow",
        "vdash",
    };

    /// <summary>Symbol to its negated counterpart (used by <c>\not</c>).</summary>
    public static readonly Dictionary<string, string> NegatedSymbols = new()
    {
        ["<"] = "≮",
        [">"] = "≯",
        ["="] = "≠",
        ["∈"] = "∉",
        ["∋"] = "∌",
        ["∣"] = "∤",
        ["∥"] = "∦",
        ["∼"] = "≁",
        ["≃"] = "≄",
        ["≅"] = "≇",
        ["≈"] = "≉",
        ["≡"] = "≢",
        ["≤"] = "≰",
        ["≥"] = "≱",
        ["≺"] = "⊀",
        ["≻"] = "⊁",
        ["⊂"] = "⊄",
        ["⊃"] = "⊅",
        ["⊆"] = "⊈",
        ["⊇"] = "⊉",
        ["⊢"] = "⊬",
        ["⊨"] = "⊭",
        ["↔"] = "↮",
        ["←"] = "↚",
        ["→"] = "↛",
        ["⇒"] = "⇏",
        ["⇐"] = "⇍",
        ["⇔"] = "⇎",
        ["≼"] = "⋠",
        ["≽"] = "⋡",
    };

    /// <summary>Blackboard-bold letters for <c>\mathbb</c>.</summary>
    public static readonly Dictionary<string, string> Blackboard = new()
    {
        ["C"] = "ℂ",
        ["H"] = "ℍ",
        ["N"] = "ℕ",
        ["P"] = "ℙ",
        ["Q"] = "ℚ",
        ["R"] = "ℝ",
        ["Z"] = "ℤ",
    };

    /// <summary>Unicode superscript characters.</summary>
    public static readonly Dictionary<string, string> Superscripts = new()
    {
        ["0"] = "⁰",
        ["1"] = "¹",
        ["2"] = "²",
        ["3"] = "³",
        ["4"] = "⁴",
        ["5"] = "⁵",
        ["6"] = "⁶",
        ["7"] = "⁷",
        ["8"] = "⁸",
        ["9"] = "⁹",
        ["+"] = "⁺",
        ["-"] = "⁻",
        ["="] = "⁼",
        ["("] = "⁽",
        [")"] = "⁾",
        ["a"] = "ᵃ",
        ["b"] = "ᵇ",
        ["c"] = "ᶜ",
        ["d"] = "ᵈ",
        ["e"] = "ᵉ",
        ["f"] = "ᶠ",
        ["g"] = "ᵍ",
        ["h"] = "ʰ",
        ["i"] = "ⁱ",
        ["j"] = "ʲ",
        ["k"] = "ᵏ",
        ["l"] = "ˡ",
        ["m"] = "ᵐ",
        ["n"] = "ⁿ",
        ["o"] = "ᵒ",
        ["p"] = "ᵖ",
        ["r"] = "ʳ",
        ["s"] = "ˢ",
        ["t"] = "ᵗ",
        ["u"] = "ᵘ",
        ["v"] = "ᵛ",
        ["w"] = "ʷ",
        ["x"] = "ˣ",
        ["y"] = "ʸ",
        ["z"] = "ᶻ",
    };

    /// <summary>Unicode subscript characters.</summary>
    public static readonly Dictionary<string, string> Subscripts = new()
    {
        ["0"] = "₀",
        ["1"] = "₁",
        ["2"] = "₂",
        ["3"] = "₃",
        ["4"] = "₄",
        ["5"] = "₅",
        ["6"] = "₆",
        ["7"] = "₇",
        ["8"] = "₈",
        ["9"] = "₉",
        ["+"] = "₊",
        ["-"] = "₋",
        ["="] = "₌",
        ["("] = "₍",
        [")"] = "₎",
        ["a"] = "ₐ",
        ["e"] = "ₑ",
        ["h"] = "ₕ",
        ["i"] = "ᵢ",
        ["j"] = "ⱼ",
        ["k"] = "ₖ",
        ["l"] = "ₗ",
        ["m"] = "ₘ",
        ["n"] = "ₙ",
        ["o"] = "ₒ",
        ["p"] = "ₚ",
        ["r"] = "ᵣ",
        ["s"] = "ₛ",
        ["t"] = "ₜ",
        ["u"] = "ᵤ",
        ["v"] = "ᵥ",
        ["x"] = "ₓ",
    };

    /// <summary>Commands that emit a space.</summary>
    public static readonly HashSet<string> SpacingCommands = new()
    {
        ",",
        ":",
        ";",
        " ",
        ">",
        "enspace",
        "enskip",
        "medspace",
        "quad",
        "qquad",
        "thickspace",
        "thinspace",
    };

    /// <summary>Commands that remove the preceding space.</summary>
    public static readonly HashSet<string> NegativeSpacingCommands = new()
    {
        "!",
        "negmedspace",
        "negthickspace",
        "negthinspace",
    };

    /// <summary>Font switches that emit nothing.</summary>
    public static readonly HashSet<string> FontSwitchCommands = new()
    {
        "bf",
        "cal",
        "it",
        "rm",
        "sf",
        "sl",
        "tt",
    };

    /// <summary>Style commands that emit nothing.</summary>
    public static readonly HashSet<string> IgnoredCommands = new()
    {
        "displaystyle",
        "limits",
        "nolimits",
        "scriptstyle",
        "scriptscriptstyle",
        "textstyle",
    };

    /// <summary>Delimiter sizing commands that emit nothing.</summary>
    public static readonly HashSet<string> SizeCommands = new()
    {
        "big",
        "Big",
        "bigg",
        "Bigg",
        "bigl",
        "Bigl",
        "biggl",
        "Biggl",
        "bigr",
        "Bigr",
        "biggr",
        "Biggr",
    };

    /// <summary>Commands that just unwrap their argument.</summary>
    public static readonly HashSet<string> PlainWrappers = new()
    {
        "emph",
        "mathcal",
        "mathbf",
        "mathfrak",
        "mathit",
        "mathrm",
        "mathnormal",
        "mathscr",
        "mathsf",
        "mathtt",
        "mathup",
        "mbox",
        "overbrace",
        "pmb",
        "smash",
        "substack",
        "text",
        "textbf",
        "textit",
        "textmd",
        "textnormal",
        "textrm",
        "textsc",
        "textsf",
        "textsl",
        "texttt",
        "textup",
        "underbrace",
        "bm",
        "boldsymbol",
    };

    /// <summary>Combining accent characters.</summary>
    public static readonly Dictionary<string, string> Accents = new()
    {
        ["acute"] = "\u0301",
        ["bar"] = "\u0305",
        ["breve"] = "\u0306",
        ["check"] = "\u030C",
        ["ddot"] = "\u0308",
        ["dot"] = "\u0307",
        ["grave"] = "\u0300",
        ["hat"] = "\u0302",
        ["mathring"] = "\u030A",
        ["overleftarrow"] = "\u20D6",
        ["overleftrightarrow"] = "\u20E1",
        ["overline"] = "\u0305",
        ["overrightarrow"] = "\u20D7",
        ["tilde"] = "\u0303",
        ["underline"] = "\u0332",
        ["vec"] = "\u20D7",
        ["widehat"] = "\u0302",
        ["widetilde"] = "\u0303",
    };

}
