namespace Pi.Tui.Components;

/// <summary>Snapshot of the editable state, used for undo (port of <c>InputState</c>).</summary>
public sealed record InputState(string Value, int Cursor);

/// <summary>Construction options for <see cref="Input"/> (port of <c>InputOptions</c>).</summary>
public sealed class InputOptions
{
    public string? Prompt { get; set; }

    public string? Placeholder { get; set; }

    /// <summary>Style applied to the placeholder text. Defaults to the identity function.</summary>
    public Func<string, string>? PlaceholderStyle { get; set; }
}

/// <summary>
/// Input component - single-line text input with horizontal scrolling (port of
/// <c>components/input.ts</c>).
///
/// Behaviour is locked by 5,447 differential vectors in <c>input-corpus.json</c>, generated by
/// running the original TypeScript implementation (see <c>docs/tui-porting-status.md</c>).
/// </summary>
public class Input : IComponent, IFocusable
{
    /// <summary>Undo coalescing state (port of the TS <c>lastAction</c> union).</summary>
    private enum LastAction
    {
        None,
        Kill,
        Yank,
        TypeWord,
    }

    private const string PasteStart = "\x1b[200~";
    private const string PasteEnd = "\x1b[201~";

    private string _value = "";
    private int _cursor;
    private readonly string _prompt;
    private readonly string _placeholder;
    private readonly Func<string, string> _placeholderStyle;
    private int _renderedStartColumn;

    public Input(InputOptions? options = null)
    {
        _prompt = options?.Prompt ?? "> ";
        _placeholder = options?.Placeholder ?? "";
        _placeholderStyle = options?.PlaceholderStyle ?? (text => text);
    }

    /// <summary>Called when the user presses Enter.</summary>
    public Action<string>? OnSubmit { get; set; }

    /// <summary>Called when the user presses Escape (or another key bound to <c>tui.select.cancel</c>).</summary>
    public Action? OnEscape { get; set; }

    /// <summary>Focusable interface - set by TUI when focus changes.</summary>
    public bool Focused { get; set; }

    // Bracketed paste mode buffering
    private string _pasteBuffer = "";
    private bool _isInPaste;

    // Kill ring for Emacs-style kill/yank operations
    private readonly KillRing _killRing = new();
    private LastAction _lastAction = LastAction.None;

    // Undo support
    private readonly UndoStack<InputState> _undoStack = new(state => state);

    /// <summary>
    /// The cursor position inside <see cref="GetValue"/>. The TS field is private; it is internal here
    /// so the differential corpus can place the cursor at arbitrary grapheme boundaries.
    /// </summary>
    internal int Cursor
    {
        get => _cursor;
        set => _cursor = value;
    }

    /// <summary>
    /// Leftmost visible column of the value after the last render. The TS field is private; it is
    /// internal here for the differential corpus.
    /// </summary>
    internal int RenderedStartColumn => _renderedStartColumn;

    public string GetValue() => _value;

    public void SetValue(string value)
    {
        _value = value;
        _cursor = Math.Min(_cursor, value.Length);
    }

    public void HandleInput(string data)
    {
        // Handle bracketed paste mode
        // Start of paste: \x1b[200~
        // End of paste: \x1b[201~

        // Check if we're starting a bracketed paste
        if (data.Contains(PasteStart, StringComparison.Ordinal))
        {
            _isInPaste = true;
            _pasteBuffer = "";
            data = ReplaceFirst(data, PasteStart, "");
        }

        // If we're in a paste, buffer the data
        if (_isInPaste)
        {
            // Check if this chunk contains the end marker
            _pasteBuffer += data;

            var endIndex = _pasteBuffer.IndexOf(PasteEnd, StringComparison.Ordinal);
            if (endIndex != -1)
            {
                // Extract the pasted content
                var pasteContent = _pasteBuffer.Substring(0, endIndex);

                // Process the complete paste
                HandlePaste(pasteContent);

                // Reset paste state
                _isInPaste = false;

                // Handle any remaining input after the paste marker
                var remaining = _pasteBuffer.Substring(endIndex + PasteEnd.Length);
                _pasteBuffer = "";
                if (remaining.Length > 0)
                {
                    HandleInput(remaining);
                }
            }
            return;
        }

        var kb = GlobalKeybindings.Get();

        // Escape/Cancel
        if (kb.Matches(data, TuiKeybindingIds.SelectCancel))
        {
            OnEscape?.Invoke();
            return;
        }

        // Undo
        if (kb.Matches(data, TuiKeybindingIds.EditorUndo))
        {
            Undo();
            return;
        }

        // Submit
        if (kb.Matches(data, TuiKeybindingIds.InputSubmit) || data == "\n")
        {
            OnSubmit?.Invoke(_value);
            return;
        }

        // Deletion
        if (kb.Matches(data, TuiKeybindingIds.EditorDeleteCharBackward))
        {
            HandleBackspace();
            return;
        }

        if (kb.Matches(data, TuiKeybindingIds.EditorDeleteCharForward))
        {
            HandleForwardDelete();
            return;
        }

        if (kb.Matches(data, TuiKeybindingIds.EditorDeleteWordBackward))
        {
            DeleteWordBackwards();
            return;
        }

        if (kb.Matches(data, TuiKeybindingIds.EditorDeleteWordForward))
        {
            DeleteWordForward();
            return;
        }

        if (kb.Matches(data, TuiKeybindingIds.EditorDeleteToLineStart))
        {
            DeleteToLineStart();
            return;
        }

        if (kb.Matches(data, TuiKeybindingIds.EditorDeleteToLineEnd))
        {
            DeleteToLineEnd();
            return;
        }

        // Kill ring actions
        if (kb.Matches(data, TuiKeybindingIds.EditorYank))
        {
            Yank();
            return;
        }
        if (kb.Matches(data, TuiKeybindingIds.EditorYankPop))
        {
            YankPop();
            return;
        }

        // Cursor movement
        if (kb.Matches(data, TuiKeybindingIds.EditorCursorLeft))
        {
            _lastAction = LastAction.None;
            if (_cursor > 0)
            {
                var beforeCursor = JsString.Slice(_value, 0, _cursor);
                var lastGrapheme = UnicodeWidth.LastGrapheme(beforeCursor);
                _cursor -= lastGrapheme is null ? 1 : lastGrapheme.Length;
            }
            return;
        }

        if (kb.Matches(data, TuiKeybindingIds.EditorCursorRight))
        {
            _lastAction = LastAction.None;
            if (_cursor < _value.Length)
            {
                var afterCursor = JsString.Slice(_value, _cursor);
                var firstGrapheme = UnicodeWidth.FirstGrapheme(afterCursor);
                _cursor += firstGrapheme is null ? 1 : firstGrapheme.Length;
            }
            return;
        }

        if (kb.Matches(data, TuiKeybindingIds.EditorCursorLineStart))
        {
            _lastAction = LastAction.None;
            _cursor = 0;
            return;
        }

        if (kb.Matches(data, TuiKeybindingIds.EditorCursorLineEnd))
        {
            _lastAction = LastAction.None;
            _cursor = _value.Length;
            return;
        }

        if (kb.Matches(data, TuiKeybindingIds.EditorCursorWordLeft))
        {
            MoveWordBackwards();
            return;
        }

        if (kb.Matches(data, TuiKeybindingIds.EditorCursorWordRight))
        {
            MoveWordForwards();
            return;
        }

        // Kitty CSI-u printable character (e.g. \x1b[97u for 'a').
        // Terminals with Kitty protocol flag 1 (disambiguate) send CSI-u for all keys, including plain
        // printable characters. Decode before the control-char check since CSI-u sequences contain
        // \x1b which would be rejected.
        var kittyPrintable = Keys.DecodeKittyPrintable(data);
        if (kittyPrintable is not null)
        {
            InsertCharacter(kittyPrintable);
            return;
        }

        // Regular character input - accept printable characters including Unicode, but reject control
        // characters (C0: 0x00-0x1F, DEL: 0x7F, C1: 0x80-0x9F).
        // The TS code iterates code points and inspects the first UTF-16 unit of each; a surrogate pair
        // starts with a high surrogate (>= 0xD800), so iterating UTF-16 units gives the same verdict.
        foreach (var ch in data)
        {
            if (ch < 32 || ch == (char)0x7f || (ch >= (char)0x80 && ch <= (char)0x9f))
            {
                return;
            }
        }

        InsertCharacter(data);
    }

    public TuiMouseEventResult? HandleMouse(TuiMouseEvent @event)
    {
        if (@event.Type != TuiMouseEventType.Press || @event.Button != TuiMouseButton.Left || @event.Y != 0)
        {
            return null;
        }
        var visibleColumn = Math.Max(0, @event.X - 2);
        var targetColumn = _renderedStartColumn + visibleColumn;
        var currentColumn = 0;
        _cursor = _value.Length;
        foreach (var (index, segment) in UnicodeWidth.GraphemesWithIndex(_value))
        {
            var nextColumn = currentColumn + UnicodeWidth.VisibleWidth(segment);
            if (targetColumn < nextColumn)
            {
                _cursor = index;
                break;
            }
            currentColumn = nextColumn;
        }
        _lastAction = LastAction.None;
        return new TuiMouseEventResult { Handled = true, Focus = true };
    }

    private void InsertCharacter(string character)
    {
        // Undo coalescing: consecutive word chars coalesce into one undo unit
        if (TextLayout.IsWhitespaceChar(character) || _lastAction != LastAction.TypeWord)
        {
            PushUndo();
        }
        _lastAction = LastAction.TypeWord;

        _value = JsString.Slice(_value, 0, _cursor) + character + JsString.Slice(_value, _cursor);
        _cursor += character.Length;
    }

    private void HandleBackspace()
    {
        _lastAction = LastAction.None;
        if (_cursor > 0)
        {
            PushUndo();
            var beforeCursor = JsString.Slice(_value, 0, _cursor);
            var lastGrapheme = UnicodeWidth.LastGrapheme(beforeCursor);
            var graphemeLength = lastGrapheme is null ? 1 : lastGrapheme.Length;
            _value = JsString.Slice(_value, 0, _cursor - graphemeLength) + JsString.Slice(_value, _cursor);
            _cursor -= graphemeLength;
        }
    }

    private void HandleForwardDelete()
    {
        _lastAction = LastAction.None;
        if (_cursor < _value.Length)
        {
            PushUndo();
            var afterCursor = JsString.Slice(_value, _cursor);
            var firstGrapheme = UnicodeWidth.FirstGrapheme(afterCursor);
            var graphemeLength = firstGrapheme is null ? 1 : firstGrapheme.Length;
            _value = JsString.Slice(_value, 0, _cursor) + JsString.Slice(_value, _cursor + graphemeLength);
        }
    }

    private void DeleteToLineStart()
    {
        if (_cursor == 0)
        {
            return;
        }
        PushUndo();
        var deletedText = JsString.Slice(_value, 0, _cursor);
        _killRing.Push(deletedText, new KillRingPushOptions
        {
            Prepend = true,
            Accumulate = _lastAction == LastAction.Kill,
        });
        _lastAction = LastAction.Kill;
        _value = JsString.Slice(_value, _cursor);
        _cursor = 0;
    }

    private void DeleteToLineEnd()
    {
        if (_cursor >= _value.Length)
        {
            return;
        }
        PushUndo();
        var deletedText = JsString.Slice(_value, _cursor);
        _killRing.Push(deletedText, new KillRingPushOptions
        {
            Prepend = false,
            Accumulate = _lastAction == LastAction.Kill,
        });
        _lastAction = LastAction.Kill;
        _value = JsString.Slice(_value, 0, _cursor);
    }

    private void DeleteWordBackwards()
    {
        if (_cursor == 0)
        {
            return;
        }

        // Save lastAction before cursor movement (MoveWordBackwards resets it)
        var wasKill = _lastAction == LastAction.Kill;

        PushUndo();

        var oldCursor = _cursor;
        MoveWordBackwards();
        var deleteFrom = _cursor;
        _cursor = oldCursor;

        var deletedText = JsString.Slice(_value, deleteFrom, _cursor);
        _killRing.Push(deletedText, new KillRingPushOptions { Prepend = true, Accumulate = wasKill });
        _lastAction = LastAction.Kill;

        _value = JsString.Slice(_value, 0, deleteFrom) + JsString.Slice(_value, _cursor);
        _cursor = deleteFrom;
    }

    private void DeleteWordForward()
    {
        if (_cursor >= _value.Length)
        {
            return;
        }

        // Save lastAction before cursor movement (MoveWordForwards resets it)
        var wasKill = _lastAction == LastAction.Kill;

        PushUndo();

        var oldCursor = _cursor;
        MoveWordForwards();
        var deleteTo = _cursor;
        _cursor = oldCursor;

        var deletedText = JsString.Slice(_value, _cursor, deleteTo);
        _killRing.Push(deletedText, new KillRingPushOptions { Prepend = false, Accumulate = wasKill });
        _lastAction = LastAction.Kill;

        _value = JsString.Slice(_value, 0, _cursor) + JsString.Slice(_value, deleteTo);
    }

    private void Yank()
    {
        var text = _killRing.Peek();
        if (string.IsNullOrEmpty(text))
        {
            return;
        }

        PushUndo();

        _value = JsString.Slice(_value, 0, _cursor) + text + JsString.Slice(_value, _cursor);
        _cursor += text.Length;
        _lastAction = LastAction.Yank;
    }

    private void YankPop()
    {
        if (_lastAction != LastAction.Yank || _killRing.Length <= 1)
        {
            return;
        }

        PushUndo();

        // Delete the previously yanked text (still at end of ring before rotation)
        var prevText = _killRing.Peek() ?? "";
        _value = JsString.Slice(_value, 0, _cursor - prevText.Length) + JsString.Slice(_value, _cursor);
        _cursor -= prevText.Length;

        // Rotate and insert new entry
        _killRing.Rotate();
        var text = _killRing.Peek() ?? "";
        _value = JsString.Slice(_value, 0, _cursor) + text + JsString.Slice(_value, _cursor);
        _cursor += text.Length;
        _lastAction = LastAction.Yank;
    }

    private void PushUndo() => _undoStack.Push(new InputState(_value, _cursor));

    private void Undo()
    {
        var snapshot = _undoStack.Pop();
        if (snapshot is null)
        {
            return;
        }
        _value = snapshot.Value;
        _cursor = snapshot.Cursor;
        _lastAction = LastAction.None;
    }

    private void MoveWordBackwards()
    {
        if (_cursor == 0)
        {
            return;
        }
        _lastAction = LastAction.None;
        _cursor = WordNavigation.FindWordBackward(_value, _cursor);
    }

    private void MoveWordForwards()
    {
        if (_cursor >= _value.Length)
        {
            return;
        }
        _lastAction = LastAction.None;
        _cursor = WordNavigation.FindWordForward(_value, _cursor);
    }

    private void HandlePaste(string pastedText)
    {
        _lastAction = LastAction.None;
        PushUndo();

        // Clean the pasted text - remove newlines and carriage returns
        var cleanText = pastedText
            .Replace("\r\n", "", StringComparison.Ordinal)
            .Replace("\r", "", StringComparison.Ordinal)
            .Replace("\n", "", StringComparison.Ordinal)
            .Replace("\t", "    ", StringComparison.Ordinal);

        // Insert at cursor position
        _value = JsString.Slice(_value, 0, _cursor) + cleanText + JsString.Slice(_value, _cursor);
        _cursor += cleanText.Length;
    }

    public void Invalidate()
    {
        // No cached state to invalidate currently
    }

    public string[] Render(int width)
    {
        // Calculate visible window
        var availableWidth = width - UnicodeWidth.VisibleWidth(_prompt);

        if (availableWidth <= 0)
        {
            return new[] { TextLayout.TruncateToWidth(_prompt, width, "") };
        }

        if (_value.Length == 0 && _placeholder.Length > 0)
        {
            var placeholder = TextLayout.TruncateToWidth(_placeholder, availableWidth, "");
            var atCursor = UnicodeWidth.FirstGrapheme(placeholder) ?? " ";
            var afterCursor = JsString.Slice(placeholder, atCursor.Length);
            var marker = Focused ? Tui.CursorMarker : "";
            var cursorChar = $"\x1b[7m{_placeholderStyle(atCursor)}\x1b[27m";
            var textWithCursor = marker + cursorChar + _placeholderStyle(afterCursor);
            var padding = new string(' ', Math.Max(0, availableWidth - UnicodeWidth.VisibleWidth(textWithCursor)));
            return new[] { _prompt + textWithCursor + padding };
        }

        var visibleText = "";
        var cursorDisplay = _cursor;
        _renderedStartColumn = 0;
        var totalWidth = UnicodeWidth.VisibleWidth(_value);

        if (totalWidth < availableWidth)
        {
            // Everything fits (leave room for cursor at end)
            visibleText = _value;
        }
        else
        {
            // Need horizontal scrolling
            // Reserve one column for cursor if it's at the end
            var scrollWidth = _cursor == _value.Length ? availableWidth - 1 : availableWidth;
            var cursorCol = UnicodeWidth.VisibleWidth(JsString.Slice(_value, 0, _cursor));

            if (scrollWidth > 0)
            {
                var halfWidth = scrollWidth / 2;
                int startCol;

                if (cursorCol < halfWidth)
                {
                    // Cursor near start
                    startCol = 0;
                }
                else if (cursorCol > totalWidth - halfWidth)
                {
                    // Cursor near end
                    startCol = Math.Max(0, totalWidth - scrollWidth);
                }
                else
                {
                    // Cursor in middle
                    startCol = Math.Max(0, cursorCol - halfWidth);
                }

                _renderedStartColumn = startCol;
                visibleText = TextLayout.SliceByColumn(_value, startCol, scrollWidth, true);
                var beforeCursor = TextLayout.SliceByColumn(_value, startCol, Math.Max(0, cursorCol - startCol), true);
                cursorDisplay = beforeCursor.Length;
            }
            else
            {
                visibleText = "";
                cursorDisplay = 0;
            }
        }

        // Build line with fake cursor
        // Insert cursor character at cursor position
        var cursorGrapheme = UnicodeWidth.FirstGrapheme(JsString.Slice(visibleText, cursorDisplay));

        var before = JsString.Slice(visibleText, 0, cursorDisplay);
        var at = cursorGrapheme ?? " "; // Character at cursor, or space if at end
        var after = JsString.Slice(visibleText, cursorDisplay + at.Length);

        // Hardware cursor marker (zero-width, emitted before fake cursor for IME positioning)
        var cursorMarker = Focused ? Tui.CursorMarker : "";

        // Use inverse video to show cursor
        var cursorChar2 = $"\x1b[7m{at}\x1b[27m"; // ESC[7m = reverse video, ESC[27m = normal
        var textWithFakeCursor = before + cursorMarker + cursorChar2 + after;

        // Calculate visual width
        var visualLength = UnicodeWidth.VisibleWidth(textWithFakeCursor);
        var padding2 = new string(' ', Math.Max(0, availableWidth - visualLength));
        return new[] { _prompt + textWithFakeCursor + padding2 };
    }

    /// <summary>
    /// JS <c>String.prototype.replace(searchString, "")</c> replaces only the first occurrence; .NET's
    /// <see cref="string.Replace(string, string)"/> replaces all of them.
    /// </summary>
    private static string ReplaceFirst(string text, string search, string replacement)
    {
        var index = text.IndexOf(search, StringComparison.Ordinal);
        return index < 0
            ? text
            : text.Substring(0, index) + replacement + text.Substring(index + search.Length);
    }
}
