using System.Text;

namespace Pi.Tui.Components;

/// <summary>A single row of a <see cref="SelectList"/> (port of the TS <c>SelectItem</c>).</summary>
public sealed record SelectItem
{
    public required string Value { get; init; }

    public required string Label { get; init; }

    public string? Description { get; init; }
}

/// <summary>
/// Styling callbacks for <see cref="SelectList"/> (port of the TS <c>SelectListTheme</c>). Every
/// callback is identity in the default theme.
/// </summary>
public sealed class SelectListTheme
{
    public required Func<string, string> SelectedPrefix { get; init; }

    public required Func<string, string> SelectedText { get; init; }

    public required Func<string, string> Description { get; init; }

    public required Func<string, string> ScrollInfo { get; init; }

    public required Func<string, string> NoMatch { get; init; }

    /// <summary>A theme whose callbacks all return their input unchanged.</summary>
    public static SelectListTheme Plain { get; } = new()
    {
        SelectedPrefix = text => text,
        SelectedText = text => text,
        Description = text => text,
        ScrollInfo = text => text,
        NoMatch = text => text,
    };
}

/// <summary>Argument passed to a custom <see cref="SelectListLayoutOptions.TruncatePrimary"/>.</summary>
public sealed record SelectListTruncatePrimaryContext(
    string Text,
    int MaxWidth,
    int ColumnWidth,
    SelectItem Item,
    bool IsSelected);

/// <summary>Column-layout knobs for <see cref="SelectList"/>.</summary>
public sealed class SelectListLayoutOptions
{
    public int? MinPrimaryColumnWidth { get; init; }

    public int? MaxPrimaryColumnWidth { get; init; }

    public Func<SelectListTruncatePrimaryContext, string>? TruncatePrimary { get; init; }
}

/// <summary>
/// Select list with filtering, scrolling and mouse support (port of
/// <c>components/select-list.ts</c>).
///
/// Behaviour is locked by 2,598 differential vectors plus a case-mapping sweep in
/// <c>select-list-corpus.json</c>, generated by running the original TypeScript implementation
/// (see <c>docs/tui-porting-status.md</c>).
/// </summary>
public class SelectList : IComponent
{
    private const int DefaultPrimaryColumnWidth = 32;
    private const int PrimaryColumnGap = 2;
    private const int MinDescriptionWidth = 10;

    private readonly SelectListTheme _theme;
    private readonly SelectListLayoutOptions _layout;
    private readonly List<SelectItem> _items;

    private List<SelectItem> _filteredItems;
    private int _selectedIndex;
    private int? _mousePressedIndex;
    private readonly int _maxVisible;

    public SelectList(
        IEnumerable<SelectItem> items,
        int maxVisible,
        SelectListTheme theme,
        SelectListLayoutOptions? layout = null)
    {
        _items = [.. items];
        _filteredItems = _items;
        _maxVisible = maxVisible;
        _theme = theme;
        _layout = layout ?? new SelectListLayoutOptions();
    }

    /// <summary>Invoked when the user confirms a row.</summary>
    public Action<SelectItem>? OnSelect { get; set; }

    /// <summary>Invoked when the user cancels (Escape or Ctrl+C).</summary>
    public Action? OnCancel { get; set; }

    /// <summary>Invoked whenever the highlighted row changes.</summary>
    public Action<SelectItem>? OnSelectionChange { get; set; }

    /// <summary>Index into the filtered rows. Exposed internally so the corpus can place it.</summary>
    internal int SelectedIndex => _selectedIndex;

    public void SetFilter(string filter)
    {
        // JS compares with ordinal startsWith on the fully-lowercased values.
        var lowerFilter = JsString.ToLowerCase(filter);
        _filteredItems = [.. _items.Where(item =>
            JsString.ToLowerCase(item.Value).StartsWith(lowerFilter, StringComparison.Ordinal))];

        // Reset selection when filter changes
        _selectedIndex = 0;
    }

    public void SetSelectedIndex(int index) =>
        _selectedIndex = Math.Max(0, Math.Min(index, _filteredItems.Count - 1));

    public void Invalidate()
    {
        // No cached state to invalidate currently
    }

    public string[] Render(int width)
    {
        var lines = new List<string>();

        // If no items match filter, show message
        if (_filteredItems.Count == 0)
        {
            lines.Add(_theme.NoMatch("  No matching commands"));
            return [.. lines];
        }

        var primaryColumnWidth = GetPrimaryColumnWidth();

        // Calculate visible range with scrolling
        var (startIndex, endIndex) = GetVisibleRange();

        // Render visible items
        for (var i = startIndex; i < endIndex; i++)
        {
            var item = _filteredItems[i];
            if (item is null)
            {
                continue;
            }

            var isSelected = i == _selectedIndex;
            var descriptionSingleLine = string.IsNullOrEmpty(item.Description)
                ? null
                : NormalizeToSingleLine(item.Description);
            lines.Add(RenderItem(item, isSelected, width, descriptionSingleLine, primaryColumnWidth));
        }

        // Add scroll indicators if needed
        if (startIndex > 0 || endIndex < _filteredItems.Count)
        {
            var scrollText = $"  ({_selectedIndex + 1}/{_filteredItems.Count})";

            // Truncate if too long for terminal
            lines.Add(_theme.ScrollInfo(TextLayout.TruncateToWidth(scrollText, width - 2, "")));
        }

        return [.. lines];
    }

    public TuiMouseEventResult? HandleMouse(TuiMouseEvent @event)
    {
        if (_filteredItems.Count == 0)
        {
            return null;
        }

        if (@event.Type == TuiMouseEventType.Wheel && @event.WheelDelta is not null and not 0)
        {
            var delta = @event.WheelDelta.Value < 0 ? -1 : 1;            var previousIndex = _selectedIndex;
            _selectedIndex = Math.Max(0, Math.Min(_filteredItems.Count - 1, _selectedIndex + delta));
            if (_selectedIndex != previousIndex)
            {
                NotifySelectionChange();
            }

            return new TuiMouseEventResult { Handled = true, Render = _selectedIndex != previousIndex };
        }

        // Hover must not change selection: the visible range is centered on it.
        if (@event.Button != TuiMouseButton.Left ||
            (@event.Type != TuiMouseEventType.Press && @event.Type != TuiMouseEventType.Click))
        {
            return null;
        }

        var (startIndex, endIndex) = GetVisibleRange();
        var itemIndex = startIndex + @event.Y;
        if (itemIndex < startIndex || itemIndex >= endIndex)
        {
            return null;
        }

        if (@event.Type == TuiMouseEventType.Press)
        {
            _mousePressedIndex = itemIndex;
            if (_selectedIndex != itemIndex)
            {
                _selectedIndex = itemIndex;
                NotifySelectionChange();
            }

            return new TuiMouseEventResult { Handled = true, Focus = true };
        }

        if (@event.Type == TuiMouseEventType.Click)
        {
            var clickedIndex = _mousePressedIndex ?? itemIndex;
            _mousePressedIndex = null;
            var changed = _selectedIndex != clickedIndex;
            _selectedIndex = clickedIndex;
            if (changed)
            {
                NotifySelectionChange();
            }

            var selectedItem = _selectedIndex >= 0 && _selectedIndex < _filteredItems.Count
                ? _filteredItems[_selectedIndex]
                : null;
            if (selectedItem is not null)
            {
                OnSelect?.Invoke(selectedItem);
            }

            return new TuiMouseEventResult { Handled = true };
        }

        return null;
    }

    public void HandleInput(string keyData)
    {
        var kb = GlobalKeybindings.Get();

        // Up arrow - wrap to bottom when at top
        if (kb.Matches(keyData, TuiKeybindingIds.SelectUp))
        {
            _selectedIndex = _selectedIndex == 0 ? _filteredItems.Count - 1 : _selectedIndex - 1;
            NotifySelectionChange();
        }

        // Down arrow - wrap to top when at bottom
        else if (kb.Matches(keyData, TuiKeybindingIds.SelectDown))
        {
            _selectedIndex = _selectedIndex == _filteredItems.Count - 1 ? 0 : _selectedIndex + 1;
            NotifySelectionChange();
        }

        // Enter
        else if (kb.Matches(keyData, TuiKeybindingIds.SelectConfirm))
        {
            var selectedItem = _selectedIndex >= 0 && _selectedIndex < _filteredItems.Count
                ? _filteredItems[_selectedIndex]
                : null;
            if (selectedItem is not null && OnSelect is not null)
            {
                OnSelect(selectedItem);
            }
        }

        // Escape or Ctrl+C
        else if (kb.Matches(keyData, TuiKeybindingIds.SelectCancel))
        {
            OnCancel?.Invoke();
        }
    }

    public SelectItem? GetSelectedItem() =>
        _selectedIndex >= 0 && _selectedIndex < _filteredItems.Count ? _filteredItems[_selectedIndex] : null;

    /// <summary>TS <c>text.replace(/[\r\n]+/g, " ").trim()</c>.</summary>
    private static string NormalizeToSingleLine(string text)
    {
        var builder = new StringBuilder(text.Length);
        var inBreak = false;
        foreach (var c in text)
        {
            if (c is '\r' or '\n')
            {
                if (!inBreak)
                {
                    builder.Append(' ');
                    inBreak = true;
                }

                continue;
            }

            inBreak = false;
            builder.Append(c);
        }

        return JsString.Trim(builder.ToString());
    }

    private static int Clamp(int value, int min, int max) => Math.Max(min, Math.Min(value, max));

    private (int StartIndex, int EndIndex) GetVisibleRange()
    {
        // JS Math.floor(maxVisible / 2) rounds towards negative infinity, unlike C# integer division.
        var halfVisible = (int)Math.Floor(_maxVisible / 2.0);
        var startIndex = Math.Max(
            0,
            Math.Min(_selectedIndex - halfVisible, _filteredItems.Count - _maxVisible));
        return (startIndex, Math.Min(startIndex + _maxVisible, _filteredItems.Count));
    }

    private string RenderItem(
        SelectItem item,
        bool isSelected,
        int width,
        string? descriptionSingleLine,
        int primaryColumnWidth)
    {
        var prefix = isSelected ? "→ " : "  ";
        var prefixWidth = UnicodeWidth.VisibleWidth(prefix);

        if (descriptionSingleLine is not null && width > 40)
        {
            var effectivePrimaryColumnWidth = Math.Max(1, Math.Min(primaryColumnWidth, width - prefixWidth - 4));
            var maxPrimaryWidth = Math.Max(1, effectivePrimaryColumnWidth - PrimaryColumnGap);
            var truncatedValue = TruncatePrimary(item, isSelected, maxPrimaryWidth, effectivePrimaryColumnWidth);
            var truncatedValueWidth = UnicodeWidth.VisibleWidth(truncatedValue);
            var spacing = new string(' ', Math.Max(1, effectivePrimaryColumnWidth - truncatedValueWidth));
            var descriptionStart = prefixWidth + truncatedValueWidth + spacing.Length;
            var remainingWidth = width - descriptionStart - 2; // -2 for safety

            if (remainingWidth > MinDescriptionWidth)
            {
                var truncatedDesc = TextLayout.TruncateToWidth(descriptionSingleLine, remainingWidth, "");
                if (isSelected)
                {
                    return _theme.SelectedText($"{prefix}{truncatedValue}{spacing}{truncatedDesc}");
                }

                var descText = _theme.Description(spacing + truncatedDesc);
                return prefix + truncatedValue + descText;
            }
        }

        var maxWidth = width - prefixWidth - 2;
        var truncated = TruncatePrimary(item, isSelected, maxWidth, maxWidth);
        if (isSelected)
        {
            return _theme.SelectedText($"{prefix}{truncated}");
        }

        return prefix + truncated;
    }

    private int GetPrimaryColumnWidth()
    {
        var (min, max) = GetPrimaryColumnBounds();
        var widestPrimary = 0;
        foreach (var item in _filteredItems)
        {
            widestPrimary = Math.Max(widestPrimary, UnicodeWidth.VisibleWidth(GetDisplayValue(item)) + PrimaryColumnGap);
        }

        return Clamp(widestPrimary, min, max);
    }

    private (int Min, int Max) GetPrimaryColumnBounds()
    {
        var rawMin = _layout.MinPrimaryColumnWidth ?? _layout.MaxPrimaryColumnWidth ?? DefaultPrimaryColumnWidth;
        var rawMax = _layout.MaxPrimaryColumnWidth ?? _layout.MinPrimaryColumnWidth ?? DefaultPrimaryColumnWidth;

        return (
            Math.Max(1, Math.Min(rawMin, rawMax)),
            Math.Max(1, Math.Max(rawMin, rawMax)));
    }

    private string TruncatePrimary(SelectItem item, bool isSelected, int maxWidth, int columnWidth)
    {
        var displayValue = GetDisplayValue(item);
        var truncatedValue = _layout.TruncatePrimary is not null
            ? _layout.TruncatePrimary(new SelectListTruncatePrimaryContext(
                displayValue, maxWidth, columnWidth, item, isSelected))
            : TextLayout.TruncateToWidth(displayValue, maxWidth, "");

        return TextLayout.TruncateToWidth(truncatedValue, maxWidth, "");
    }

    /// <summary>TS <c>item.label || item.value</c>: an empty label falls back to the value.</summary>
    private static string GetDisplayValue(SelectItem item) =>
        string.IsNullOrEmpty(item.Label) ? item.Value : item.Label;

    private void NotifySelectionChange()
    {
        var selectedItem = GetSelectedItem();
        if (selectedItem is not null && OnSelectionChange is not null)
        {
            OnSelectionChange(selectedItem);
        }
    }
}
